services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: teste-splan-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ${DATABASE_VOLUME_PATH}:/var/lib/postgresql/data  